server.port: 8009

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/testDB
    username: sa
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update